name: Build and release Systemd sysext images
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      # allow the action to create a release
      contents: write
    steps:
      # checkout the sources
      - uses: actions/checkout@v3
      # build the images and generate a manifest
      - name: Build
        run: |
          set -euo pipefail

          images=(
              "teleport-9.3.26"
              "teleport-10.3.16"
              "teleport-11.3.22"
              "teleport-14.1.5"
          )

          for image in ${images[@]}; do
              component="${image%-*}"
              version="${image#*-}"
              "./create_${component}_sysext.sh" "${version}" "${component}"
              mv "${component}.raw" "${image}.raw"
          done

          sha256sum *.raw > SHA256SUMS
      - name: Get git tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.2

      - name: (Draft)Release check
        run: |
          if [[ ${{ steps.tag.outputs.tag }} =~ ^[0-9]+$ ]]; then
             echo "TAG_TYPE=numeric" >> $GITHUB_ENV
          else
             echo "TAG_TYPE=alphanumeric" >> $GITHUB_ENV
          fi

      # create a Github release with the generated artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        if: env.TAG_TYPE == 'numeric'
        with:
          files: |
            SHA256SUMS
            *.raw
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        if: env.TAG_TYPE == 'alphanumeric'
        with:
          draft: true
          files: |
            SHA256SUMS
            *.raw
      - name: Blinky
        run: |
          curl -o /dev/null https://app.getblinky.io/api/v1/ingest/webhook/be6f78fd-ca93-4642-8bae-678f73eb0014

  multi-build:
    name: Multi version build
    runs-on: ubuntu-22.04
    container:  mediadepot/flatcar-developer:${{ matrix.flatcarversion }}
    strategy:
      max-parallel: 6
      matrix:
        flatcarversion: ["3602.2.0", "3602.2.1"]
    permissions:
      # allow the action to create a release
      contents: write
    steps:
      # checkout the sources
      - uses: actions/checkout@v3
      # build the images and generate a manifest
      - name: Build
        run: |
          set -euo pipefail

          images=(
              "zfs-2.1.12-${{ matrix.flatcarversion }}"
          )

          for image in ${images[@]}; do
              component="${image%%-*}"
              flatcarversion="${image##*-}"
              temp="${image#*-}"
              version="${temp%-*}"
              "./create_${component}_sysext.sh" "${version}" "${component}" "${flatcarversion}"
              mv "${component}.raw" "${image}.raw"
          done

          sha256sum *.raw > SHA256SUMS
      - name: Get git tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.2

      - name: (Draft)Release check
        run: |
          if [[ ${{ steps.tag.outputs.tag }} =~ ^[0-9]+$ ]]; then
             echo "TAG_TYPE=numeric" >> $GITHUB_ENV
          else
             echo "TAG_TYPE=alphanumeric" >> $GITHUB_ENV
          fi

      # create a Github release with the generated artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        if: env.TAG_TYPE == 'numeric'
        with:
          files: |
            SHA256SUMS
            *.raw
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        if: env.TAG_TYPE == 'alphanumeric'
        with:
          draft: true
          files: |
            SHA256SUMS
            *.raw
